name: ptit-chat-frontend
region: sin

static_sites:
  - name: frontend
    # GitHub repository configuration
    github:
      repo: ptit-ttcs2025/fe-chat-app
      branch: main
      deploy_on_push: true

    # Build configuration
    build_command: npm run build
    output_dir: dist

    # Environment variables
    envs:
      - key: VITE_API_BASE_URL
        value: https://ttcs-chat-app-z86ml.ondigitalocean.app/api/v1
      - key: VITE_WS_URL
        value: wss://ttcs-chat-app-z86ml.ondigitalocean.app/api/v1/ws
      - key: VITE_IMAGE_URL
        value: /assets/img/
      - key: VITE_APP_VERSION
        value: "1.0.0"
      - key: NODE_ENV
        value: production

    # Routes
    routes:
      - path: /

    # Catchall route for React Router
    catchall_document: index.html
#     output_dir: dist
#     environment_slug: node-js
#     routes:
#       - path: /

